### ISSUE TITLE
Create a list of privileges for professors

### ISSUE THREAD

**Issue by Jnxiong04** [CMU-313/fall23-nodebb-jasta#24]
- We would like to create of list containing all of the privileges a professor will have on NodeBB. A professor should have access to everything
- This is a low effort task
- There are no dependencies for this task
- Acceptance Criteria: A list of privileges has been created with each element being a 1 representing that the professor has the privilege. This list should be attached to each professor.

**Comment by s026134** [comment]
ALREADY IN CODEBASE
